# Generated by Django 6.1.1 on 2026-09-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовка'),
        ),
    ]
