# Generated by Django 6.1.1 on 2026-09-24 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskside', '0003_alter_comment_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickethistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'История заявки', 'verbose_name_plural': 'Истории заявок'},
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='new_value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='old_value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
