# Generated by Django 6.1.1 on 2026-09-24 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskside', '0004_alter_tickethistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickethistory',
            options={},
        ),
    ]
