# Generated by Django 6.1.1 on 2026-09-24 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskside', '0005_alter_tickethistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickethistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'История заявки', 'verbose_name_plural': 'Истории заявок'},
        ),
    ]
