# Generated by Django 6.1.1 on 2026-09-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskside', '0006_alter_tickethistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Низкий'), ('MEDIUM', 'Средний'), ('HIGH', 'Высокий'), ('CRITICAL', 'Критический')], default='LOW', max_length=8, verbose_name='Приоритет'),
        ),
    ]
